name: ML Pipeline CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # FIX: ensures repo recognized as DVC repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "dvc[all]"

      - name: Run DVC pipeline
        run: dvc repro

      - name: Show metrics
        run: dvc metrics show

      - name: Upload metrics artifact
        uses: actions/upload-artifact@v4
        with:
          name: dvc-metrics
          path: metrics.json
